### ISSUE TITLE
Implement "Add accounts"

### ISSUE THREAD

**Issue by io7m** [NYPL-Simplified/android#113]
... instead of Join Accounts.

This involves:
1. Capturing the error code `E_ADEPT_CORE_USER_NOT_ACTIVATED` on fulfillment and informing the user that they need to add the relevant account. Unfortunately, we have no way of knowing which, and must assume that the user knows which account we mean.
2. A small view in Settings that shows which accounts are active/available, and a means to set the password for each.
3. Signing in with each listed account on login, instead of just the NYPL account.

**Comment by gioneill** [comment]
Specific feature is no longer applicable. Multi-library handles multiple adobe authorizations. Some of this research could be useful if we ever decide to union the book lists into one "My Books" tab, however.
