### ISSUE TITLE
Facets should not persist when going up in the catalog

### ISSUE THREAD

**Issue by gwendolen** [NYPL-Simplified/android#165]
Instead, the client should act like it does on iOS where the previously retrieved feed is shown. It should _not_ use the parent link in the present OPDS feed (or whatever it is that seems to be used currently).

This was reported to me by @jce1028. I'll need to do some investigation before I fully understand what the problem is and what needs to be changed.

**Comment by aferditamuriqi** [comment]
this was fixed when the up navigation was removed.
