### ISSUE TITLE
Change preloaded titles

### ISSUE THREAD

**Issue by gwendolen** [NYPL-Simplified/android#169]
_From @jce1028 on January 11, 2016 21:35_

Preloaded Content
Reduce the number of preloaded titles to 3
Pride and Predjudice
Sherlock Holmes
Moby Dick

_Copied from original issue: NYPL/Simplified#7_

**Comment by winniequinn** [comment]
@benanderman, the best way to do this would involve adding a Git submodule for the new `NYPL-Simplified/preloaded-content` repository and pulling things in that way.
