### ISSUE TITLE
Retrieve username and barcode from patron info dump

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/android#172]
https://github.com/NYPL/Simplified-circulation/issues/24 will establish a new API endpoint that serves detailed information about a patron.

Client software needs to know how to fetch this info, process it, and store it locally until the patron logs out.

As a motivating case, if the patron logs on with their NYPL username, then goes to look at their settings, this new controller is how you find out what their barcode is. And vice versa if the patron logs on with their barcode.

**Comment by gioneill** [comment]
Do we have a use-case for this issue other than receiving the user's barcode number? That is currently being accomplished by reading the authorization id from the opds loans feed.

**Comment by leonardr** [comment]
Yes, I think the authorization ID in the OPDS loans feed is how we decided to handle this, and we never created that endpoint, so this issue can be closed.
