### ISSUE TITLE
Unable to easily update Bugsnag to 3.3.0 (we are on 3.2.7)

### ISSUE THREAD

**Issue by JCCR** [NYPL-Simplified/android#175]
Bugsnag published a new release in Central, and it's no longer packaging `jar` artifacts only an `aar`.
It also has a new sub-dependency on com.android.support>support-annotations

I deployed the support lib to nexus using the maven android sdk deployer, and got past a POM missing issue, but now there's problems with the DEX step which I can't resolve as easily.

Posting this as an issue for future reference.

**Comment by aferditamuriqi** [comment]
#193

**Comment by gioneill** [comment]
covered by #468 
using gradle build may ease the transition
