### ISSUE TITLE
Fix pagination and bookmark accuracy

### ISSUE THREAD

**Issue by jce1028** [NYPL-Simplified/android#187]
There is a substantial performance enhancement to Readium's CFIs which are used for bookmarks and highlights.  The CFI improvements are targeted for Readium .23.  We are currently on .20.  Readium Main is .22.  We need to implement.23 to pull in the CFI and bookmark bug fixes for Readium.

**Comment by aferditamuriqi** [comment]
multi library version is now on readium 25
