### ISSUE TITLE
Add About Page url to Circ Manager

### ISSUE THREAD

**Issue by jce1028** [NYPL-Simplified/android#190]
The following copy needs to be implemented in the NYPL SimplyE application.  This is basically copy that would normally be in the App store however, it is requested/required to be placed in NYPL's version of Library Simplified.

Under Settings, a new section would be placed above "Acknowledgements" titled "About" which would open a simple Web View that will display copy hosted at www.librarysimplified.org/appabout.html
this url will be published along with similar links at the bottom of the OPDS feed page.

**Comment by leonardr** [comment]
The server side code of this is written. The 'about' link will start showing up in feeds once the configuration file is changed and redeployed. Then it's a matter of picking up the link and rendering it.

**Comment by winniequinn** [comment]
@leonardr I have separate tickets for implementing the about page for each app. If your work is done then feel free to close this ticket.
