### ISSUE TITLE
Rendering problem for "Where'd You Go, Bernadette" (3M ID arzkw89)

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/android#237]
Reported by Michael Santangelo on Android. Probably a Readium problem?

**Comment by aferditamuriqi** [comment]
@leonardr the book looks good to me, do you have more specific information ?

**Comment by leonardr** [comment]
I think the book just didn't render. It's possible Michael got the audiobook by mistake--I remember he somehow got an audiobook into Simplified. If it works for you let's close the issue.
