### ISSUE TITLE
Issue in NYPL-Simplified/android 

### ISSUE THREAD

**Issue by ashishdixitmca** [NYPL-Simplified/android#264]
Hi anyone can help me to execute this NYPL -Simplified -Android  lib I per my understanding there is no Android launcher only maven project I tried to build from maven-android-sdk-deployer but not able to build getting error in all pom.xml file.
If any thing they can provide like Sample Android Application or Android Sdk Launcher then It will be greate to see how to work with this lib.

**Comment by ArsalanMP** [comment]
i have same problem anyone can help me?
