### ISSUE TITLE
Make project public

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/android#274]
Every part of this project except the Adobe DRM connector should be made public. We need to review the code for any licensing problems, make sure the README is helpful, and flip the switch. Same thing we did with the server components.

**Comment by aferditamuriqi** [comment]
@leonardr this project has been public even before i started working on it.

**Comment by leonardr** [comment]
You're right. Gwen said both Android and iOS were private but looking at the project group I see that only the DRM portions of Android are private.
