### ISSUE TITLE
//Detail page should render thumbnail image, not full-size image

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/android#292]
I thought this had been fixed but it hasn't and in fact there's no issue for it.

When the patron taps on a book to see the detail view, the client shows the full-size image (i.e. the one in the "image" link). But there's no reason to do this because the image is rendered at the size of a thumbnail.

It would be better to always use the thumbnail, because a) the full-size image can be quite large, b) you've already retrieved the thumbnail so there's no extra HTTP request, c) I have done a lot of work to make sure that the thumbnail URL is always good, but there are a lot of reasons why the full-size image URL might not be good, so the current behavior often makes it look like the image suddenly goes missing when you go into detail view.

**Comment by aferditamuriqi** [comment]
I have double checked this and we do not render full size images.
