### ISSUE TITLE
Removing app from a device doesn't take patron below Adobe device limit

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/android#304]
A SimplyE patron reported reaching the Adobe device limit, removing SimplyE from one of their devices, but still being at the device limit.

I'm keeping the details of the message out of this public issue. It's not clear from the message whether the patron has SimplyE installed on two devices or four. Either way, they should be fine since the limit is six.

**Comment by leonardr** [comment]
Aferdita confirms that uninstalling the app does not deregister the device. That makes sense in retrospect but it's not what I was expecting or what a patron would expect.

**Comment by winniequinn** [comment]
There is nothing we can do about this, I'm afraid. There is no way to install hooks to fire when apps are uninstalled.
