### ISSUE TITLE
Allow folks to use app offline

### ISSUE THREAD

**Issue by jce1028** [NYPL-Simplified/android#309]
Curretnly, a person want to read a book and they are in the subway and they start the app, it attempts to connect to the internet and update the bookshelf.  This prohibits them from accessing the books they already downloaded because the view does not revert to the saved state.

**Comment by aferditamuriqi** [comment]
this is resolved in https://github.com/NYPL-Simplified/android/tree/multi_library_develop

the books have to be downloaded though. and the catalog view will still show not connected to the internet.
