### ISSUE TITLE
E_ADEPT_REQUEST_EXPIRED despite device time being set correctly

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/android#313]
Patron reports getting E_ADEPT_REQUEST_EXPIRED when activating their device with Adobe. Patron claims their device time is set correctly (clock skew being the most common cause of E_ADEPT_REQUEST_EXPIRED) and has tried uninstalling and reinstalling the app. Patron's credentials were successfully used to activate a different device.

Device information:

```
Device brand: SM-G900H
Android version: 21
App package :org.nypl.simplified.simplye
App version :1013 
```

**Comment by gioneill** [comment]
@leonardr If we still have any thread on this user, I would recommend the full uninstallation steps that also involve clearing app data and caches in the Android Settings Panel.

So: 
- Update app to latest version
- Logout
- Go to settings: apps: storage: clear app data and caches
- Uninstall
- Go back to google play store, download fresh, and try to sign in again

- Also, the user is given permission to create a new library card just for simplye through the card creator interface

**Comment by leonardr** [comment]
Since this was more than a year ago I think it's better to leave this closed.
