### ISSUE TITLE
PDF Works on Android are displayed without an button.

### ISSUE THREAD

**Issue by jce1028** [NYPL-Simplified/android#354]
There should be consistency in the behavior of iOS and Android when it comes to displaying works of the PDF media type or unsupported media type.  This is especially apparent in graphic novels and comic books.  Android presents these works without a button to "reserve" or "get."  This could be perceived as a bug.  Android should simply not display those works because they are unsupported media types just as iOS does.  Why show someone something they can not possibly borrow or read in SimplyE.

**Comment by aferditamuriqi** [comment]
https://github.com/NYPL-Simplified/android/commit/4b4b6d5955992f64c244db5d35f7edad6ec37f64

**Comment by aferditamuriqi** [comment]
this has been implemented already
