### ISSUE TITLE
confusing age verification msg

### ISSUE THREAD

**Issue by daryanypl** [NYPL-Simplified/android#358]
I download new SimplyE, and open the InstantClassics catalog.  I get a dialog that says: "Age Verification
You must be 13 years of age or older to download a book form the collection.  How old are you?"
And then I can chose "under 13" or "13 or older".  Both options are valid, and would show me each its own catalog, so the "must be 13" message is confusing.  Let's rephrase to something like: "You must be 13 or older to download some of the books in this collection.  How old are you?"

**Comment by aferditamuriqi** [comment]
this need to be addressed in iOS as well. https://github.com/NYPL-Simplified/Simplified-iOS/issues/541

**Comment by daryanypl** [comment]
Matt's fix didn't make it into master.  Closing as duplicate of https://github.com/NYPL-Simplified/android/issues/568 .
