### ISSUE TITLE
re-downloading fails

### ISSUE THREAD

**Issue by daryanypl** [NYPL-Simplified/android#360]
I downloaded from the NYPL catalog "How to Tell If Your Cat Is Plotting to Kill You" (it seemed important).  I then uninstalled the simplye app, and side-loaded the next apk.  Now, I see the book in "My Books", but when I click the "Download" button, I get a "The download could not be completed." error message.

**Comment by gioneill** [comment]
After investigating, this was an expected result during our testing. It was at a time when Adobe ID's were getting crossed between different libraries (BK would check out an NYPL book, etc.). This has since been resolved and won't affect patrons using the apps in the store.
