### ISSUE TITLE
card creator crash on reverse

### ISSUE THREAD

**Issue by daryanypl** [NYPL-Simplified/android#361]
I went through the steps to create a new card in card creator.  Then clicked the "back" triangle button a few screens.  Then clicked the "next" links to advance the card creator again.  At the last screen, I was told that my username is unavailable (which is correct, expected behavior bc I'd already created that username), the the app crashed.

**Comment by gioneill** [comment]
Unable to reproduce under the following scenarios:

1. Go through card creator and create new account.
2. Hit Android back button back to beginning.
3. Move forward again.
- Also tried cycling between using Android back button and "prev" button when moving backward.
- Also tried using an existing account on the first attempt.

**Comment by aferditamuriqi** [comment]
i am closing this, since it can't be reproduced.
