### ISSUE TITLE
downloads disappeared

### ISSUE THREAD

**Issue by daryanypl** [NYPL-Simplified/android#364]
I'm not sure if I can reproduce this, but I'll watch out for it.  Here's what I know:
- I was using apk 1024.
- I was using my "darya1" username account.
- I had a few My Books, all of them from NYPL catalog, two of them were downloaded onto my phone.
- I was reading one book, then went back to see the catalog.
- I left the app for half a day, and used other apps.  When I came back to continue reading, 
all the items in My Books had "Download" buttons next to them, as if they weren't already on the phone.
- I clicked the Download button for the book I was reading, but the download kept stalling at 0%.
- I force-quit and restarted the app.
- Now the two books I already had on the device were properly showing up with "Read" buttons next to them in My Books.

**Comment by aferditamuriqi** [comment]
can this be re-tested on 1085 to ensure this is not a problem anymore.
