### ISSUE TITLE
Catch-all issue for book-specific rendering problems

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/android#365]
Problem reported with "The Siren" by Tiffany Reisz as distributed by Overdrive.

Inside cover image renders properly. Text of the book is garbage. TOC works properly but every chapter is nothing but binary characters.

The same book renders properly in the Overdrive app and in Overdrive Read.

This may also be a problem on iOS.

**Comment by leonardr** [comment]
See also https://github.com/NYPL-Simplified/Simplified-iOS/issues/433

**Comment by leonardr** [comment]
Problem reported for the Bibliotheca edition of "Indigo Slam". This is Bibliotheca ID d3u6589, not the Overdrive edition (which NYPL also has).

"The bottoms and tops of my book pages are cut off when I use the SimplyE app."

The Overdrive edition works fine.

```
Device Information:
iPad
iOS 10.2

App information:
org.nypl.labs.SimplyE
Version 1.0.3 
```

**Comment by daryanypl** [comment]
This might be related to that sporadic rendering problem we think is DRM decryption messing up.

**Comment by leonardr** [comment]
I observed a problem in the Overdrive edition of "Hannah's Choice" by Emma Miller. It's one I think we've seen a couple times before--you can't get past a certain page, which is blank. Choosing a chapter from the TOC has no effect.

**Comment by leonardr** [comment]
Overdrive edition of "Submit to Desire" (3c956d9a-6ed7-43e8-b323-16bf17a4cd42) renders as gibberish. TOC is blank. This one is interesting because I have _also_ seen Overdrive give weird responses for this book through its API (though I don't know what the responses looked like).

**Comment by leonardr** [comment]
But for the record, here's the bit I did see:

```
  File "./api/overdrive.py", line 253, in fulfill
    patron, pin, licensepool.identifier.identifier, internal_format)
  File "./api/overdrive.py", line 321, in get_fulfillment_link
    patron, pin, download_link)
  File "./api/overdrive.py", line 335, in get_fulfillment_link_from_download_link
    return self.extract_content_link(download_response.json())
  File "./api/overdrive.py", line 338, in extract_content_link
    link = content_link_gateway_json['links']['contentlink']
```

**Comment by leonardr** [comment]
Overdrive edition of "Rich Bitch" by Nicole Lapin. TOC works, cover page image works, every chapter renders as gibberish.

**Comment by winniequinn** [comment]
I spent some time looking into "The Siren" by Tiffany Reisz today on iOS and did not have much luck. It seems like non-HTML resources are being decrypted fine and HTML resources become garbage. There is some HTML-specific code in RDServices but I believe the data is garbage before it even gets there. I do not have time to look into this further right now, sadly.

**Comment by leonardr** [comment]
Problem reported with "Lucky" by Henry Chang (ISBN 9781616957841). Entire book is blank. Seems to work on Overdrive Read.

**Comment by leonardr** [comment]
Problem reported with "Angry Tide" by Winston Graham. Entire book is blank.

**Comment by gioneill** [comment]
With increasing evidence over time, it's pretty clear this was always the result of a failed DRM activation. Android typically produced books with the garbled text, and iOS as "blank" books. Having book be blank on Android may point to different behavior based on the book provider.

We can more quickly return to this on a per-issue basis now that steps hae been taken to reduce these situations, as well as further work to reduce DRM activations.

**Comment by leonardr** [comment]
Over the weekend, while reading a book in the subway I got the book stuck in the blank state, presumably due to a connection issue. The problem seemed pretty durable at the time, but when I tried it again this morning in preparation for showing it to you, I was able to open the book.

**Comment by gioneill** [comment]
One possibility is that a loan has "expired", but would still show up as a title that could be read in "My Books" because the device was offline when it was opened. So because we support offline reading, the book would look readable, but was actually no longer in the loan period, so shows up as blank (not decrypted).

Perhaps we can add some kind of device-local timer that would still remove the book from the My Books section even if the device does not have a chance to update via the Loans Feed. (Or at least test this hypothesis to see if the same symptom occurs). I've created #518 for this task.
