### ISSUE TITLE
Audiobook Phase 1

### ISSUE THREAD

**Issue by aferditamuriqi** [NYPL-Simplified/android#387]
Phase 1 of: https://github.com/NYPL-Simplified/android/issues/162

- create an audio book player with some standard controls (play, stop, pause, next, prev. etc.)
- implement standard UI elements (cover, titles, time elapsed,  time remaining etc.)
- use a local audiobook (download from https://librivox.org for example)
- show the Table of content for the audio book currently playing  
- indicate current chapter playing in TOC
- play audio in background

- ui for a list of audiobooks (multiple local audiobooks)

**Comment by gioneill** [comment]
@daryanypl Is this ticket still applicable? I would either edit/split this up for yourself, or close and link it to your open tickets.

**Comment by daryanypl** [comment]
Nah, I keep audiobook issues in their own project.  Closing.
