### ISSUE TITLE
Binary garbled output when re-checking out a book that is returned

### ISSUE THREAD

**Issue by jbdalton** [NYPL-Simplified/android#398]
Saw this behavior in random titles checked out: 

1. checkout book
2. read normal output
3. return
4. check out again (immediately or after a few minutes ) 
5. see garbled output

For 4.), I don't know what the exact time limit is yet, after which the download corrects itself. But after an hour I have been able to download a legible copy again.  So the problem does correct itself somewhere between a few minutes and an hour.

![overdrive_garbled1](https://cloud.githubusercontent.com/assets/1854259/24929817/54876a50-1ed5-11e7-9b82-01f697fda926.JPG)

**Comment by gioneill** [comment]
Happens when DRM decryption has failed due to a missing Adobe activation with that account. These types of issues have mostly been addressed in recent months. But we can open the issue with a specific account and title if this issue returns.
