### ISSUE TITLE
implement bookmarking across devices

### ISSUE THREAD

**Issue by aferditamuriqi** [NYPL-Simplified/android#404]
retrieving, syncing , adding and deleting of bookmarks needs to be implemented based on users sync settings. sync settings have already been implemented on QA, and also client side, make sure once this task is being addressed that this works as required on production. in order to work on this on QA, a separate library entry needs to be added to the library chooser (accounts). 

referencing https://github.com/NYPL-Simplified/Simplified/issues/23

**Comment by gioneill** [comment]
New sprint issues created for feature.
