### ISSUE TITLE
DRM books show garbage content

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/android#428]
This is only happening with internal builds. @gioneill and I both have been able to reproduce it from a clean slate, although @aferditamuriqi reports that it works for her.

**Comment by aferditamuriqi** [comment]
this seems to be a very broad statement. it works for me based on the information I was given, and also it works for several other developers. so more information as of what does not work, as well as some details which books, or all books, etc would be helpful to narrow down this issue, if there is an issue, there is more conversation about this in slack as well.
