### ISSUE TITLE
Page Turning Performance and Response

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/android#467]
Tap response (either the detection or ability to act on it) is a very inconsistent target on the right and left sides of the screen. Roughly around half the taps do not ever result in a page being turned. The swipe gesture also is not turning pages at all. This results in a frustrating experience for the average user trying to go through a book on Android.

**Comment by elizabethyalkut** [comment]
I can duplicate this bug. LG K8 V, running Android 7.0.

**Comment by winniequinn** [comment]
Closed by #480.
