### ISSUE TITLE
Progress indicator goes back when advancing chapters

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/android#469]
It seems the algorithm for the progress indicator is not correct. It moves up each time you flip a page, but then it jumps back a bit when you hit the next chapter. Presumably someone tries to take into account the current chapter as well as the position within the current chapter and just messed up the math. 

This affects both SimplyE and Open eBooks.

**Comment by gioneill** [comment]
It could probably be a separate issue, but I know it would be pretty valuable to show "total book progress" and I believe that is what most readers expect to see in any kind of visual representation of progress. This has also been discussed with implementations paired with Readium inside a few different discussions on their repo page.

**Comment by winniequinn** [comment]
@gioneill This is what the Android app attempts to do right now. It's just not doing it very well.
