### ISSUE TITLE
Switch Gradle to use `implementation` instead of `compile`

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/android#507]
As of Gradle 4.0, `compile` is deprecated and `implementation` should be used instead. Given that `implementation` handles transitive dependencies differently though, this will require a good deal more than a simple find and replace. See this page for more information:

https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

**Comment by gioneill** [comment]
@daryanypl We've been linking issues to the PR directly by marking "resolve" or "fixes" and then the issue number. That way the ticket's open/closed status will follow the status of the PR.

I think it's fine to leave this one closed.
