### ISSUE TITLE
EULA Checkbox on Card Creator Missing

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/android#513]
It is a small screen, so that's one possibility.
Also, the "next" button is typically enabled when the EULA checkbox is already checked.

![img_2403](https://user-images.githubusercontent.com/6179695/34443601-39e14ad8-ec96-11e7-8e25-3d26c854c384.JPG)

**Comment by daryanypl** [comment]
Looks like the checkbox is there, and the view holding the radio buttons and the checkbox has a scroll bar.  But the scroll bar isn't visible unless the user scrolls.  Will put the whole screen on the scroll bar, and make the scroll bar visible.

**Comment by daryanypl** [comment]
![screenshot_1523979227](https://user-images.githubusercontent.com/18293410/38880627-2b787b9e-4234-11e8-8cef-ca7a51fcc316.png)

**Comment by daryanypl** [comment]
Fixed scroll bar.
