### ISSUE TITLE
Don't show search interface when a feed is not searchable

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/android#538]
Android version of https://github.com/NYPL-Simplified/Simplified-iOS/issues/939

**Comment by leonardr** [comment]
This issue was already fixed in iOS but is still present on Android. The search box is present but tapping the search icon does nothing, since there's no way to search.

**Comment by daryanypl** [comment]
I think that appearing and disappearing a core UI element would be confusing to the user.  I'd prefer to show the search box and icon, but make it clear that they are purposely disabled.  I will speak with UX to get their opinion.

**Comment by daryanypl** [comment]
fixed, waiting verification data
