### ISSUE TITLE
Titles distributed through bearer token exchange don't show up in "My Books" and can't be fulfilled

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/android#572]
I have borrowed "Drowned by Corn" from qa.circulation.librarysimplified.org. This is a title distributed by Plympton through bearer token exchange, implemented on Android by https://github.com/NYPL-Simplified/android/issues/493. The title shows up in my `/loans` feed.

On iOS 2.2.8, the title shows up in "My Books". I can fulfill this title and read it. When I search for the title, the button label is "Read", implying that SimplyE knows I have the book on loan. Everything seems fine.

On Android 2.1.6, the title does not show up in "My Books". I see the title in search results, but the button lable is "Get" (implying that SimplyE does not know I already have the book on loan), and I cannot fulfill it. The error when I try to fulfill is "The download could not be completed." 

https://github.com/NYPL-Simplified/android/issues/537 could cause this problem, but that issue has been fixed, and it doesn't explain why a book I have on loan doesn't show up in "My Books".

**Comment by winniequinn** [comment]
This is my work, so I'd like to look into this one with @daryanypl.

**Comment by winniequinn** [comment]
@leonardr I'll have to grab you for this one because I'm not able to reproduce it.

I wonder if maybe you ran into this issue while using the custom URL functionality in the app. If I rebuild the app so it uses the QA URL by default, I am able to check out the book, sign out of the account, sign back in, see it in my bookshelf, and download it again without issue.

**Comment by leonardr** [comment]
Yes, I did run into the issue while using the custom URL functionality. If the app has different behavior when a custom URL is specified through the interface, than when the same URL is compiled in, that's a little problematic for me.

I'll import the collection into the NYPL production server, add the collection to NYPL, test it with the stock app, and if there's a problem I'll just remove the collection from NYPL.

**Comment by leonardr** [comment]
After adding the Plympton collection to NYPL's production circulation manager I've been able to search for, borrow, fulfill and read Plympton books on both iOS and Android. So this was a phantom problem.

However, we should not have had to spend so much time on a phantom problem. I'm closing this issue and filing https://github.com/NYPL-Simplified/android/issues/579 to deal with the underlying issue.
