### ISSUE TITLE
Instant Classics post-search feed lacks search link?

### ISSUE THREAD

**Issue by daryanypl** [NYPL-Simplified/android#588]
Choose SimplyE Classics catalog, click the search icon, type a keyword and search.  The search results page comes up.  This page doesn't itself have a search view box.  Possibly because the search link is missing from the opds feed that comes in.

**Comment by leonardr** [comment]
You're right, the OPDS feed for search results doesn't itself contain a search link. The problem will be fixed when we switch over to the feed at https://circulation.librarysimplified.org/CLASSICS/, so I'm going to close this issue.
