### ISSUE TITLE
Reader: UI is hard to open in media-dense test EPUBs

### ISSUE THREAD

**Issue by io7m** [NYPL-Simplified/android#62]
The UI opens when the user taps on something that isn't a link or anything clickable. The problem in those EPUBs is that everything on the page is clickable.

**Comment by winniequinn** [comment]
Presently, the UI does not toggle so this is not an issue. In the future, we will take a more iBooks-like approach to the UI where there are reserved areas on the top and bottom, thus alleviating any potential problems with media-dense EPUBs.
